Fix flaky testSetResetGlobalSetting
The test could sometimes fail with:

    Error executing stmt=select settings from sys.cluster args=null error=org.postgresql.util.PSQLException:
    ERROR: [query] Data too large, data for [hash-join: 12] would be [2099414/2mb], which is larger than the limit of [2097152/2mb]

Given that the test only asserts that the setting can be changed and is
not related to query breaking or accounting behavior it's fine to
increase the limit that is being set.

The PostgreSQL client can do some `pg_catalog` queries up-front, and we
recently increased the amount of rows returned in some cases. So it's
feasible to assume that the amount of required memory increased for
these queries.