Improve error message for deserializing unknown type id
Relates to https://github.com/crate/crate/issues/19704

`lttb` uses the `LttbStateType` which is missing on older nodes, causing
failures when it tries to read the collect phase:

    NullPointerException[Cannot invoke "org.elasticsearch.common.io.stream.Writeable$Reader.read(org.elasticsearch.common.io.stream.StreamInput)" because the return value of "java.util.Map.get(Object)" is null]
    java.lang.NullPointerException: Cannot invoke "org.elasticsearch.common.io.stream.Writeable$Reader.read(org.elasticsearch.common.io.stream.StreamInput)" because the return value of "java.util.Map.get(Object)" is null
    at io.crate.types.DataTypes.fromStream(DataTypes.java:266)
    at io.crate.execution.dsl.phases.AbstractProjectionsPhase.<init>(AbstractProjectionsPhase.java:124)

(cherry picked from commit 89c1b0b105a0944838f979d8399d2fea7dd7282b)