tests: Try to include jobs-log information in stuck tasks assertion error
There are occasional test failures like
`testRestoreEmptyPartitionedTableUsingALL`:

    java.lang.AssertionError: ## node: node_sc4
    {e66bb76b-156d-d2f8-cf52-28be5a8e93a0=Task{id=e66bb76b-156d-d2f8-cf52-28be5a8e93a0, tasks=[DistResultRXTask{id=1, numBuckets=1, isDone=false}], closed=false}}

    	at __randomizedtesting.SeedInfo.seed([E86E12E22654DE54:47D455E736DF12]:0)
    	at io.crate.integrationtests.SQLIntegrationTestCase.assertNoTasksAreLeftOpen(SQLIntegrationTestCase.java:342)
    	at jdk.internal.reflect.GeneratedMethodAccessor87.invoke(Unknown Source)
    	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
    	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
    	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
    	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
    	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    	at java.base/java.lang.Thread.run(Thread.java:833)
    Caused by: java.lang.AssertionError:
    Expected: is <0>
         but: was <1>
    	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
    	at org.junit.Assert.assertThat(Assert.java:964)
    	at org.junit.Assert.assertThat(Assert.java:930)
    	at io.crate.integrationtests.SQLIntegrationTestCase.lambda$assertNoTasksAreLeftOpen$0(SQLIntegrationTestCase.java:299)
    	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:755)
    	at io.crate.integrationtests.SQLIntegrationTestCase.assertNoTasksAreLeftOpen(SQLIntegrationTestCase.java:294)
    	... 9 more
    	Suppressed: java.lang.AssertionError:

This is an attempt to get more information from a failure.