Fix resolveNodeId error handling in ShardDMLExecutor
`resolveNodeId` in `ShardDMLExecutor` could raise an exception that
wasn't caught by `BatchIteratorBackpressureExecutor`. This could lead to
an operation getting stuck.

`testInsertToPartitionFromQuery` failed with:

    java.lang.AssertionError: All incoming requests on node [node_s1] should have finished. Expected 0 but got 2456
    Expected: <0L>
         but: was <2456L>
            at __randomizedtesting.SeedInfo.seed([10627E584D438717:877660B1673F5B1]:0)
            at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
            at org.junit.Assert.assertThat(Assert.java:964)
            at org.elasticsearch.test.InternalTestCluster.lambda$assertRequestsFinished$38(InternalTestCluster.java:2219)
            at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:741)
            at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:715)
            at org.elasticsearch.test.InternalTestCluster.assertRequestsFinished(InternalTestCluster.java:2216)
            at org.elasticsearch.test.InternalTestCluster.assertAfterTest(InternalTestCluster.java:2195)
            at org.elasticsearch.test.ESIntegTestCase.afterInternal(ESIntegTestCase.java:440)
            at org.elasticsearch.test.ESIntegTestCase.cleanUpCluster(ESIntegTestCase.java:1299)

and:

    Cause 5: com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=997, name=cratedb[node_s1][scheduler][T#10], state=RUNNABLE, group=TGRP-PartitionedTableIntegrationTest]
    Caused by: [bs..partitioned.my_table.04132/tZM4exSMQkqYr8f-BLh7MQ] org.elasticsearch.index.IndexNotFoundException: no such index
            at __randomizedtesting.SeedInfo.seed([10627E584D438717]:0)
            at app//org.elasticsearch.cluster.routing.RoutingTable.shardRoutingTable(RoutingTable.java:150)
            at app//io.crate.execution.engine.indexing.ShardDMLExecutor.resolveNodeId(ShardDMLExecutor.java:123)
            at app//io.crate.execution.engine.indexing.ShardDMLExecutor.lambda$apply$4(ShardDMLExecutor.java:160)
            at app//io.crate.execution.engine.indexing.BatchIteratorBackpressureExecutor.resumeConsumption(BatchIteratorBackpressureExecutor.java:214)

(cherry picked from commit a20de159e50d2d0a6cb48053f7f325085eb1e4a9)