Fix flaky AbstractAsyncTaskTests.testAutoRepeat
There was a race leading to:

    WARNING: Uncaught exception in thread: Thread[#46,cratedb[AbstractAsyncTaskTests][generic][T#2],5,TGRP-AbstractAsyncTaskTests]
    java.lang.AssertionError: interrupted
    	at __randomizedtesting.SeedInfo.seed([DCD8FFF276897349]:0)
    	at org.elasticsearch.common.util.concurrent.AbstractAsyncTaskTests$1.runInternal(AbstractAsyncTaskTests.java:74)
    	at org.elasticsearch.common.util.concurrent.AbstractAsyncTask.run(AbstractAsyncTask.java:143)
    	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1095)
    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:619)
    	at java.base/java.lang.Thread.run(Thread.java:1447)

This could be reproduced adding a sleep after the
`assertThat(count.get()).isEqualTo(1);`. The problem was that the
`runInternal` could move to the `barrier1.await()` in the second
iteration before the `barrier1.reset()` call outside happened.