Fix NoSuchFileException in BlobPathITest
    java.lang.RuntimeException: java.nio.file.NoSuchFileException: /tmp/io.crate.integrationtests.BlobPathITest_7A754858D6AC20B7-001/tableBlobPath-002/nodes/0/indices/1MYszJZiSAGGTPtV_wBUFQ/0/blobs/tmp
    	at __randomizedtesting.SeedInfo.seed([7A754858D6AC20B7:BCA62349D8F56702]:0)
    	at io.crate.integrationtests.BlobIntegrationTestBase.lambda$assertNoTmpFilesAndNoIndicesRemaining$0(BlobIntegrationTestBase.java:87)
    	at io.crate.integrationtests.BlobIntegrationTestBase.forEachIndicesMap(BlobIntegrationTestBase.java:101)
    	at io.crate.integrationtests.BlobIntegrationTestBase.lambda$assertNoTmpFilesAndNoIndicesRemaining$1(BlobIntegrationTestBase.java:76)
    	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:703)
    	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:689)
    	at io.crate.integrationtests.BlobIntegrationTestBase.assertNoTmpFilesAndNoIndicesRemaining(BlobIntegrationTestBase.java:76)
    	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
    	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
    	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:1004)
    	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
    	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:299)
    	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:293)
    	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
    	at java.base/java.lang.Thread.run(Thread.java:1589)
    Caused by: java.nio.file.NoSuchFileException: /tmp/io.crate.integrationtests.BlobPathITest_7A754858D6AC20B7-001/tableBlobPath-002/nodes/0/indices/1MYszJZiSAGGTPtV_wBUFQ/0/blobs/tmp
    	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
    	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
    	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
    	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
    	at org.apache.lucene.tests.mockfile.WindowsFS.getKey(WindowsFS.java:59)
    	at org.apache.lucene.tests.mockfile.WindowsFS.onOpen(WindowsFS.java:66)
    	at org.apache.lucene.tests.mockfile.HandleTrackingFS.callOpenHook(HandleTrackingFS.java:82)
    	at org.apache.lucene.tests.mockfile.HandleTrackingFS.newDirectoryStream(HandleTrackingFS.java:332)
    	at java.base/java.nio.file.Files.newDirectoryStream(Files.java:482)
    	at java.base/java.nio.file.Files.list(Files.java:3791)
    	at io.crate.integrationtests.BlobIntegrationTestBase.lambda$assertNoTmpFilesAndNoIndicesRemaining$0(BlobIntegrationTestBase.java:82)
    	... 14 more