Fix handling of columns of type undefined during alter table
Alter table still uses the deprecated
`DocTableInfoFactory.create` overload that uses `IndexMetadata` to
verify the settings after an upgrade.

If the table contained a column with name ``undefined`` it was mapped to
``not_supported`` instead of ``undefined`` due to a missing type mapping
entry. It then failed on ``storageSupport`` leading to an error:

    UnsupportedOperationException: Type NOT SUPPORTED does not support storage

Closes https://github.com/crate/crate/issues/19065

(cherry picked from commit dba1a90c820411058f2d5889339ea74986976e9b)