Skip toolchain download on GHA
We setup a matching JDK and the foojay API used by the toolchain plugin
is occasionally acting up:

    [INFO] Required toolchain: jdk [ vendor='temurin' version='26.0.2.1' ]
    [INFO] Begin to install JDK 26.0.2.1
    [ERROR] Failed to download and install JDK
    java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at jdk.internal.util.Preconditions.outOfBounds (Preconditions.java:100)
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex (Preconditions.java:106)
        at jdk.internal.util.Preconditions.checkIndex (Preconditions.java:302)
        at java.util.Objects.checkIndex (Objects.java:365)
        at java.util.ArrayList.get (ArrayList.java:428)
        at com.google.gson.JsonArray.get (JsonArray.java:203)
        at org.apache.maven.plugins.toolchain.FoojayService.parseFileNameAndDownloadUrl (FoojayService.java:145)

(cherry picked from commit 0ca9f65685673a16e132b2d767c41e5ccb9829b2)

# Conflicts:
#	.github/workflows/main.yml