Reduce number of shards in testHealthWithClosedIndices
Depending on node randomization, the large amount of replicas in the
test case can lead to slow allocation or even errors (shard lock),
leading to a timeout on a `alter table ... close`, causing flaky test
failures:

    org.elasticsearch.ElasticsearchTimeoutException: Timeout while running `alter table t3 close`
    	at __randomizedtesting.SeedInfo.seed([967E12237D9C33DA:AC4F34795F25B86D]:0)
    	at app//io.crate.testing.SQLTransportExecutor.executeTransportOrJdbc(SQLTransportExecutor.java:197)
    	at app//io.crate.testing.SQLTransportExecutor.exec(SQLTransportExecutor.java:137)
    	at app//org.elasticsearch.test.IntegTestCase.execute(IntegTestCase.java:1698)
    	at app//org.elasticsearch.test.IntegTestCase.execute(IntegTestCase.java:1834)
    	at app//org.elasticsearch.cluster.ClusterHealthIT.testHealthWithClosedIndices(ClusterHealthIT.java:134)

This sets the number of shards for the table to 1 to mitigate the issue.