Fix handling of closed partitions on INSERT .. FROM VALUES
The cluster block check used equals, which didn't cover the cluster
block created in:

https://github.com/crate/crate/blob/e6bac64550317ffa6d9d1e8dd875dbf1e7ecc5a4/server/src/main/java/io/crate/execution/ddl/tables/TransportCloseTable.java#L373-L383

`testInsertIntoClosedPartition` was flaky because of this and failed
with:

    org.elasticsearch.cluster.block.ClusterBlockException: blocked by: [FORBIDDEN/4/Table or partition preparing to close. Reopen the table to allow writes again or retry closing the table to fully close it.];
    	at __randomizedtesting.SeedInfo.seed([774DB56220DFE1CE:3BC95ADA0E5BE]:0)
    	at app//org.elasticsearch.cluster.block.ClusterBlocks.indexBlockedException(ClusterBlocks.java:207)
    	at app//org.elasticsearch.action.support.replication.TransportReplicationAction.blockExceptions(TransportReplicationAction.java:245)
    	at app//org.elasticsearch.action.support.replication.TransportReplicationAction$ReroutePhase.doRun(TransportReplicationAction.java:632)
    	at app//org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
    	at app//org.elasticsearch.action.support.replication.TransportReplicationAction.doExecute(TransportReplicationAction.java:173)
    	at app//org.elasticsearch.action.support.replication.TransportReplicationAction.doExecute(TransportReplicationAction.java:90)
    	at app//org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:51)
    	at app//io.crate.planner.operators.InsertFromValues.execute(InsertFromValues.java:714)
    	at app//io.crate.planner.operators.InsertFromValues.lambda$execute$0(InsertFromValues.java:285)
    	at java.base@17.0.2/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187)
    	at java.base@17.0.2/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309)
    	at app//io.crate.planner.operators.InsertFromValues.execute(InsertFromValues.java:281)
    	at app//io.crate.action.sql.Session.singleExec(Session.java:679)
    	at app//io.crate.action.sql.Session.exec(Session.java:542)
    	at app//io.crate.action.sql.Session.triggerDeferredExecutions(Session.java:516)
    	at app//io.crate.action.sql.Session.sync(Session.java:500)
    	at app//io.crate.testing.SQLTransportExecutor.execute(SQLTransportExecutor.java:265)
    	at app//io.crate.testing.SQLTransportExecutor.execute(SQLTransportExecutor.java:243)
    	at app//io.crate.testing.SQLTransportExecutor.executeTransportOrJdbc(SQLTransportExecutor.java:189)
    	at app//io.crate.testing.SQLTransportExecutor.exec(SQLTransportExecutor.java:136)
    	at app//io.crate.integrationtests.SQLIntegrationTestCase.execute(SQLIntegrationTestCase.java:432)
    	at app//io.crate.integrationtests.SQLIntegrationTestCase.execute(SQLIntegrationTestCase.java:589)
    	at app//io.crate.integrationtests.PartitionedTableIntegrationTest.testInsertIntoClosedPartition(PartitionedTableIntegrationTest.java:197)

(cherry picked from commit aed002c60a16d136cf6b8fd98fed9237f74aca36)