tests: Fix flaky test_types_with_storage_can_be_inserted_and_queried (numeric)
Flakiness was caused by Numeric data generation, because previously,
scale could be > numDigits that was selected randomly. Use scale from
the type as a minumum number of digits.

failure e.g.:
```
java.lang.IllegalArgumentException: Scale of numeric must be less than the precision. NUMERIC(19, 21) is unsupported.
    at __randomizedtesting.SeedInfo.seed([DD1858AE87042B54:F806A5D2595F59EA]:0)
    at io.crate.types.NumericType.<init>(NumericType.java:79)
    at io.crate.types.DataTypes.guessType(DataTypes.java:318)
    at io.crate.testing.DataTypeTesting.extendedType(DataTypeTesting.java:276)
    at io.crate.integrationtests.TransportSQLActionTest.test_types_with_storage_can_be_inserted_and_queried(TransportSQLActionTest.java:1944)
    at java.base/java.lang.reflect.Method.invoke(Method.java:580)
    at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1758)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:946)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:982)
    at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:996)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
    at java.base/java.lang.Thread.run(Thread.java:1570)
```