Fix error thrown when deleting/updating an empty parted table.
UnsupportedFeatureException: Delete projection can only be executed on a shard] and
UnsupportedFeatureException: Update projection can only be executed on a shard] where
thrown instead of 0 rows returned when deleting or updating by Query an empty partitioned
table (partitions list -> empty).