Fix flaky testRepeatedFetchDoesNotLeakSysJobsLog
    org.postgresql.util.PSQLException: ERROR: java.lang.AssertionError: Previous resultReceiver must be finished
    	at __randomizedtesting.SeedInfo.seed([CA8B61AE5F09E570:8F064BB0D7D0517D]:0)
    	at app//org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2674)
    	at app//org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2364)
    	at app//org.postgresql.core.v3.QueryExecutorImpl.fetch(QueryExecutorImpl.java:2560)
    	at app//org.postgresql.jdbc.PgResultSet.next(PgResultSet.java:2077)
    	at app//io.crate.integrationtests.PostgresITest.testRepeatedFetchDoesNotLeakSysJobsLog(PostgresITest.java:925)

(cherry picked from commit f101f751d4a0ecb608254d3f346082e41d4e8ec4)