Fix handling of bitstring params when creating views
`Literal.fromObject` didn't handle `bitstring` values - creating a
`StringLiteral` with the bitstring value instead. For `CREATE VIEW`
statements containing parameter placeholders `Literal.fromObject` is
used to inline the values for the placeholders. Due to the missing
handling, that step failed.

`Literal.fromObject` is also used in a few other places (`show create
table` to convert setting values), but these are unproblematic as far as
I can tell.

With asyncpg this caused failures like:

    xs = asyncpg.BitString('0101')
    await conn.execute("create view v1 as select ?::bit(4)", xs)
    asyncpg.exceptions.InternalServerError: Cannot cast `'B''0101'''` of type `text` to type `bit(4)`

(cherry picked from commit 6bb4d282993f396f7273c2dc9b1daf9d7e44850b)