Fix flaky test_doc_values_write_and_read_roundtrip_inclusive_doc_mapper_parse
The test failed with seed `8DB195BC45C84F34:485630A4B34D9594`, because
the type randomized to length 1 and the random value generator produced
longer values. For example:

    java.lang.IllegalArgumentException: 'IwCrRpCjeW' is too long for the text type of length: 1