Fix RamAccounting calculation for grouping by primitives.
1. Previously, the RamAccounting took place took place on every
   row by adding the overhead per row. The Maps used though are
   expanding by doubling the size once a certain threshold is reached.
   This resulted in OutOfMemory exceptions. E.g.::

     SQLActionException: 500 Internal Server Error 5000 OutOfMemoryError: Java heap space
	at io.netty.util.collection.IntObjectHashMap.rehash(IntObjectHashMap.java:457)
	at io.netty.util.collection.IntObjectHashMap.growSize(IntObjectHashMap.java:395)
	at io.netty.util.collection.IntObjectHashMap.put(IntObjectHashMap.java:128)
	at io.netty.util.collection.IntObjectHashMap.put(IntObjectHashMap.java:312)
	at io.netty.util.collection.IntObjectHashMap.put(IntObjectHashMap.java:37)
	at io.crate.execution.engine.aggregation.GroupBySingleNumberCollector.addWithAccounting(GroupBySingleNumberCollector.java:243)

   The problem is solved by RamAccounting in batches at the point
   that the HashMap is about to grow (double its size).

2. The bytes calculated per Object[] holding the grouping states
    was 16 instead of 24 which also lead to OutOfMemory exceptions.