Fix issue with PG ser/deser of BigDecimal.ZERO
Fix BigDecimal.ZERO, which has zero digits, to be handled correctly
in PG binary serialization and deserialization.

Additionally, BigDecimal cannot take values of NaN or infinity,
for example `new BigDecimal(Double.NaN)` throws an error. Also,
it's not allowed to try to set directly a value like that to a numeric
column when using JDBC:

```
PreparedStatement preparedStatement =
    conn.prepareStatement( "INSERT INTO t (l) VALUES (?)");
preparedStatement.setDouble(1, Double.POSITIVE_INFINITY);
```
as it throws:
```
org.postgresql.util.PSQLException: ERROR: Cannot cast value `Infinity` to type `numeric`
``

Therfore, simplify the logic and remove code which handles
`NaN` and `Infinities`.

Fixes: #16797
(cherry picked from commit 991a74a6c6feec30f3f5768459967d6502ba0a58)

# Conflicts:
#	docs/appendices/release-notes/5.9.1.rst