Fix test_jmx on java > 11
Need to add exports to avoid errors like:

    java.lang.IllegalAccessError: class org.gridkit.jvmtool.JmxConnectionInfo (in unnamed module @0x7a5d012c) cannot access class sun.rmi.server.UnicastRef