Fix repository verification error handling
The cause can be `null` in which case the following NPE happened:

    NullPointerException[Cannot invoke "Object.getClass()" because the return value of "java.lang.Exception.getCause()" is null]
    java.lang.NullPointerException: Cannot invoke "Object.getClass()" because the return value of "java.lang.Exception.getCause()" is null
    	at org.elasticsearch.repositories.blobstore.BlobStoreRepository.startVerification(BlobStoreRepository.java:888)

(cherry picked from commit ce2c2081a2b0670a312666f0518f26e1a95925e4)