Fix length 0 bulkArgs handling in test layer
Follow up to https://github.com/crate/crate/pull/12521
`test_snapshot_with_corrupted_shard_index_file` failed:

    java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
    	at __randomizedtesting.SeedInfo.seed([3393D83462AF076B:35D6B6DD03A19B57]:0)
    	at io.crate.data.RowN.get(RowN.java:53)
    	at io.crate.analyze.SymbolEvaluator.lambda$visitParameterSymbol$0(SymbolEvaluator.java:74)
    	at io.crate.expression.scalar.arithmetic.ArrayFunction.evaluate(ArrayFunction.java:81)
    	at io.crate.expression.FunctionExpression.value(FunctionExpression.java:50)
    	at io.crate.expression.tablefunctions.ValuesFunction$ValuesTableFunctionImplementation.iteratorsFrom(ValuesFunction.java:104)
    	at io.crate.expression.tablefunctions.ValuesFunction$ValuesTableFunctionImplementation.lambda$evaluate$0(ValuesFunction.java:98)
    	at io.crate.expression.tablefunctions.ColumnOrientedRowsIterator.iterator(ColumnOrientedRowsIterator.java:43)
    	at java.base/java.lang.Iterable.spliterator(Iterable.java:101)
    	at io.crate.planner.operators.InsertFromValues.evaluateValueTableFunction(InsertFromValues.java:548)
    	at io.crate.planner.operators.InsertFromValues.execute(InsertFromValues.java:232)
    	at io.crate.action.sql.Session.singleExec(Session.java:676)
    	at io.crate.action.sql.Session.exec(Session.java:539)
    	at io.crate.action.sql.Session.triggerDeferredExecutions(Session.java:513)
    	at io.crate.action.sql.Session.sync(Session.java:497)
    	at io.crate.testing.SQLTransportExecutor.execute(SQLTransportExecutor.java:294)
    	at io.crate.testing.SQLTransportExecutor.executeBulk(SQLTransportExecutor.java:540)
    	at io.crate.testing.SQLTransportExecutor.execBulk(SQLTransportExecutor.java:148)
    	at io.crate.integrationtests.SQLIntegrationTestCase.execute(SQLIntegrationTestCase.java:576)
    	at io.crate.integrationtests.SnapshotRestoreIntegrationTest.test_snapshot_with_corrupted_shard_index_file(SnapshotRestoreIntegrationTest.java:633)

(cherry picked from commit 8043f7787c5769887b400ec1c64c5d0c33e78dc9)