Try fix flaky testIteratorDoesNotHandleRejectedExecutionException
Follow up to https://github.com/crate/crate/commit/a7d451b726fdeb7a86bbd582f9b0f5e7a4ddb7f3
The test was still flaky:

    Error:  Failures:
    Error:    AsyncCompositeBatchIteratorTest.testIteratorDoesNotHandleRejectedExecutionException:105
    Expecting
      <CompletableFuture[Completed: [[0],
        [1],
        [0],
        [1],
        [0],
        [1],
        [0],
        [1],
        [2],
        [3],
        [2],
        [3],
        [2],
        [3],
        [2],
        [3],
        [4],
        [4],
        [4],
        [4]]]>
    to have failed within 100L MILLISECONDS.
    Be aware that the state of the future in this message might not reflect the one at the time when the assertion was performed as it is evaluated later on

New assumption: Due to scheduling it could happen that the single thread
could serve all `loadNextBatch()` calls.

Solution: Force rejected execution with a custom executor.