Favor object unknown exceptions over missing privileges
This changes the privilege checks to throw `SchemaUnknownException` or
`RelationUnknown` instead of `MissingPrivilegeException` if the current
user is not allowed to see the objects in question. This is done to
prevent information leaks due to slightly different error messages. For
example, previously the following errors were raised:

    select * from does_exist;
    MissingPrivilegeException: Missing 'DQL' privilege for user 'arthur']

    select * from does_NOT_exist;
    MissingPrivilegeException: Missing privilege for user 'arthur'

If a user has visibility permissions (= any of `DDL`, `DQL`, or `DML`)
then the user still gets a more detailed `MissingPrivilegeException`,
like `Missing 'DQL' privilege for user ...`.