Fix flaky testTransientErrorsDuringRecoveryAreRetried
`finalizeReceived` wasn't set correctly to `true`, leading to:

    Caused by: java.lang.IllegalStateException: Recovery cannot be started twice
            at org.elasticsearch.indices.recovery.IndexRecoveryIT$SingleStartEnforcer.accept(IndexRecoveryIT.java:886)
            at org.elasticsearch.indices.recovery.IndexRecoveryIT.lambda$testTransientErrorsDuringRecoveryAreRetried$6(IndexRecoveryIT.java:784)
            at org.elasticsearch.test.transport.StubbableTransport$WrappedConnection.sendRequest(StubbableTransport.java:238)
            at org.elasticsearch.transport.TransportService.sendRequestInternal(TransportService.java:617)
            ... 10 more

Which could cause the test to fail with:

    java.lang.AssertionError: timed out waiting for green state

It wasn't set correctly because the `handlingBehavior` is set for a
specific action:

    addRequestHandlingBehavior(recoveryActionToBlock, handlingBehavior)

Depending on the randomization of `recoveryActionToBlock`, the following
condition was always false: `actionName.equals(PeerRecoveryTargetService.Actions.FINALIZE)`