Try fix flaky testPreferCopyCanPerformNoopRecovery
Follow up to https://github.com/crate/crate/pull/18282

The `(long)` cast can fail if the shard is unassigned:

    java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because "io.crate.testing.SQLResponse.rows()[0][0]" is null
    	at __randomizedtesting.SeedInfo.seed([49768D28A0298C03:D649A4DEDCF0C1EE]:0)
    	at org.elasticsearch.gateway.ReplicaShardAllocatorIT.lambda$ensureActivePeerRecoveryRetentionLeasesAdvanced$0(ReplicaShardAllocatorIT.java:398)

(This also changes the expression in ShardRowContext to be non-nullable,
because `seqNoStats` can never be null)