Fix field order determinism in Indexer & DocTableinfo
The order of the fields in the source wasn't deterministic.

The `ObjectIndexer` uses the `innerTypes` of an `ObjectType` if present
but these innerTypes weren't ordered by position. This led to a
different order between indexing of dynamic values and indexing after
the mapping update.

This could trigger an assertion, causing flaky test failures:

    WARNING: Uncaught exception in thread: Thread[#915,cratedb[node_s0][generic][T#5],5,TGRP-InsertIntoIntegrationTest]
    java.lang.AssertionError: seqNo [0] was processed twice in generation [2], with different data. prvOp [Index{id='qh3x24YBsqY9ANFaFJux', seqNo=0, primaryTerm=1, version=1, autoGeneratedIdTimestamp=-1}], newOp [Index{id='qh3x24YBsqY9ANFaFJux', seqNo=0, primaryTerm=1, version=1, autoGeneratedIdTimestamp=-1}]
    	at __randomizedtesting.SeedInfo.seed([164B6F142ED3CEC8]:0)
    	at org.elasticsearch.index.translog.TranslogWriter.assertNoSeqNumberConflict(TranslogWriter.java:253)
    	at org.elasticsearch.index.translog.TranslogWriter.add(TranslogWriter.java:217)
    	at org.elasticsearch.index.translog.Translog.add(Translog.java:519)
    	at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:940)
    	at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:806)
    	at org.elasticsearch.index.shard.IndexShard.applyIndexOperation(IndexShard.java:752)
    	at org.elasticsearch.index.shard.IndexShard.applyTranslogOperation(IndexShard.java:1375)
    	at org.elasticsearch.index.shard.IndexShard.applyTranslogOperation(IndexShard.java:1362)
    	at org.elasticsearch.indices.recovery.RecoveryTarget.lambda$indexTranslogOperations$2(RecoveryTarget.java:379)
    [...]
    caused by: java.lang.RuntimeException: stack capture previous op
	at org.elasticsearch.index.translog.TranslogWriter.assertNoSeqNumberConflict(TranslogWriter.java:258)
	at org.elasticsearch.index.translog.TranslogWriter.add(TranslogWriter.java:217)
	at org.elasticsearch.index.translog.Translog.add(Translog.java:519)
	at org.elasticsearch.index.engine.InternalEngine.index(InternalEngine.java:940)
	at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:806)
	at org.elasticsearch.index.shard.IndexShard.index(IndexShard.java:778)
	at io.crate.execution.dml.upsert.TransportShardUpsertAction.processRequestItemsOnReplica(TransportShardUpsertAction.java:376)
	at io.crate.execution.dml.upsert.TransportShardUpsertAction.processRequestItemsOnReplica(TransportShardUpsertAction.java:101)