Fix handling of missing indexMetadata in createMultiShardScoreDocCollector
Fixes the flaky test `MetadataTrackerITest.test_deleted_partition_is_replicated`

Failed with:

    java.lang.NullPointerException: Cannot invoke "org.elasticsearch.cluster.metadata.IndexMetadata.getIndex()" because the return value of "org.elasticsearch.cluster.metadata.Metadata.index(String)" is null
    	at __randomizedtesting.SeedInfo.seed([DAF7CE9C990E194C:3B74E831F40DDD04]:0)
    	at io.crate.execution.engine.collect.sources.ShardCollectSource.createMultiShardScoreDocCollector(ShardCollectSource.java:317)
    	at io.crate.execution.engine.collect.sources.ShardCollectSource.getIterator(ShardCollectSource.java:260)
    	at io.crate.execution.engine.collect.MapSideDataCollectOperation.createIterator(MapSideDataCollectOperation.java:58)
    	at io.crate.execution.engine.collect.CollectTask.start(CollectTask.java:162)
    	at io.crate.execution.jobs.RootTask.start(RootTask.java:191)
    	at io.crate.execution.jobs.transport.TransportJobAction.nodeOperation(TransportJobAction.java:103)
    	at io.crate.execution.jobs.transport.TransportJobAction.nodeOperation(TransportJobAction.java:50)
    	at io.crate.execution.support.NodeActionRequestHandler.messageReceived(NodeActionRequestHandler.java:48)
    	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:59)
    	at org.elasticsearch.transport.InboundHandler$RequestHandler.doRun(InboundHandler.java:257)
    	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    	at java.lang.Thread.run(Thread.java:833)