Fix trace logging of negative byte values in ChildMemoryCircuitBreaker
The `ByteSizeValue` constructor doesn't permit negative values.
Activating trace logging for the breaker package resulted in exceptions:

    SQLParseException[Values less than -1 bytes are not supported: -2097152b]
    io.crate.exceptions.SQLParseException: Values less than -1 bytes are not supported: -2097152b

(cherry picked from commit 566f02b82127ec6ef5d418d3325e61e1b829d02f)