Fix handling of BitString in undefined type serialization
Changes in https://github.com/crate/crate/pull/13181 to include the
``bit`` type in more random tests made the `TransportSQLActionTest`
flaky, failing with errors like:

    org.opentest4j.AssertionFailedError: [All incoming requests on node [node_sd5] should have finished]
    expected: 0L
     but was: 16440L

The root cause was a bug causing a streaming error:

    Cause 1: java.io.IOException: can not write type [class io.crate.sql.tree.BitString]
            at org.elasticsearch.common.io.stream.StreamOutput.writeGenericValue(StreamOutput.java:742)
            at io.crate.types.UndefinedType.writeValueTo(UndefinedType.java:85)
            at io.crate.types.ObjectType.writeValueTo(ObjectType.java:275)
            at io.crate.types.ObjectType.writeValueTo(ObjectType.java:59)
            at io.crate.execution.dml.upsert.ShardUpsertRequest$Item.writeTo(ShardUpsertRequest.java:434)
            at io.crate.execution.dml.upsert.ShardUpsertRequest.writeTo(ShardUpsertRequest.java:179)