Fix NPE in IsNullPredicate.refExistsQuery
Failed on CI with:

    java.lang.NullPointerException: Cannot invoke "io.crate.metadata.Reference.column()" because "ref" is null
    	at __randomizedtesting.SeedInfo.seed([7D3270BB542E42BF:D74A6C7F027CB2F6]:0)
    	at io.crate.expression.predicate.IsNullPredicate.refExistsQuery(IsNullPredicate.java:132)
    	at io.crate.expression.predicate.IsNullPredicate.refExistsQuery(IsNullPredicate.java:167)
    	at io.crate.expression.predicate.NotPredicate.toQuery(NotPredicate.java:197)
    	at io.crate.lucene.LuceneQueryBuilder$Visitor.visitFunction(LuceneQueryBuilder.java:245)
    	at io.crate.lucene.LuceneQueryBuilder$Visitor.visitFunction(LuceneQueryBuilder.java:231)
    	at io.crate.expression.symbol.Function.accept(Function.java:185)
    	at io.crate.lucene.LuceneQueryBuilder.convert(LuceneQueryBuilder.java:121)
    	at io.crate.execution.engine.collect.count.InternalCountOperation.syncCount(InternalCountOperation.java:154)
    	at io.crate.execution.engine.collect.count.InternalCountOperation.lambda$prepareGetCount$2(InternalCountOperation.java:137)
    	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    	at java.lang.Thread.run(Thread.java:1589)

Couldn't reproduce the failure locally, but `DocTableInfo` instances are
cached until there is a clusterState change event, so it's likely caused
by a race condition. Added a unit test to cover the scenario