Fix flaky testVersioningPromotedReplica
    ./gradlew :server:test -Dtests.seed=E18DF1CA7400DE8E -Dtests.class=org.elasticsearch.index.engine.InternalEngineTests -Dtests.nightly=true -Dtests.method="testVersioningPromotedReplica" -Dtests.nightly=true -Dtests.locale=kok-IN -Dtests.timezone=America/Atikokan

Failed with:

    java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "text" is null
    	at __randomizedtesting.SeedInfo.seed([E18DF1CA7400DE8E:79091B746B064DDF]:0)
    	at org.apache.lucene.util.BytesRef.<init>(BytesRef.java:84)
    	at org.apache.lucene.index.Term.<init>(Term.java:70)
    	at org.elasticsearch.index.engine.InternalEngineTests.assertOpsOnPrimary(InternalEngineTests.java:2108)
    	at org.elasticsearch.index.engine.InternalEngineTests.testVersioningPromotedReplica(InternalEngineTests.java:2209)

In the scenario there are two index operations and `versionConflict` got
randomized to true twice - never setting `lastFieldValue`