Operate on consistent clusterState in shard upsert action
There were three `clusterService.state()` lookups during the primary
operation and two during the replica operation.

Each call could return a different state, I suspect this could lead to
the following assertion triggering:

    com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=1284, name=Thread-33, state=RUNNABLE, group=TGRP-PartitionedTableConcurrentIntegrationTest]
    at __randomizedtesting.SeedInfo.seed([3E15C895F91C936B:9D00ACB541C9E476]:0)
    Caused by: org.elasticsearch.common.io.stream.NotSerializableExceptionWrapper: AssertionError: IndexMetadata for index hWvcWd_MQiiaK8_5KNSMNw not found in cluster state
    at __randomizedtesting.SeedInfo.seed([3E15C895F91C936B]:0)
    at io.crate.execution.dml.upsert.TransportShardUpsertAction.processRequestItems(TransportShardUpsertAction.java:142)

Because the first state had a relationMetadata entry, but in the next
state it was gone because the partiton was deleted. This triggered the
assertion instead of the expected `RelationUnknown` error, leading to
`test_stress_partition_deletion_and_creation` failures