Fix NPE in maybeRefreshReaders
Follow up to 3aaa741bab643fe5c23f07c203915ebb160d428a

Some tests got flaky, e.g. `io.crate.integrationtests.MetadataTrackerITest.test_deleted_partition_is_replicated`

    java.lang.NullPointerException: Cannot invoke "org.elasticsearch.index.IndexService.getShard(int)" because "indexService" is null
    	at __randomizedtesting.SeedInfo.seed([1FC73DD75B589FAC:FE441B7A365B5BE4]:0)
    	at io.crate.execution.jobs.SharedShardContexts.maybeRefreshReaders(SharedShardContexts.java:83)
    	at io.crate.execution.engine.fetch.FetchTask.start(FetchTask.java:229)
    	at io.crate.execution.jobs.RootTask.start(RootTask.java:198)
    	at io.crate.execution.jobs.RootTask.start(RootTask.java:184)
    	at io.crate.execution.engine.JobLauncher.setupTasks(JobLauncher.java:268)
    	at io.crate.execution.engine.JobLauncher.execute(JobLauncher.java:172)
    	at io.crate.planner.operators.LogicalPlanner.executeNodeOpTree(LogicalPlanner.java:536)