Fix index-/shard not found error handling in TransportSyncRetentionLeasesAction
Follow up to https://github.com/crate/crate/pull/18341
Exceptions were not caught within the runnable, leading to failures:

    org.opentest4j.MultipleFailuresError:
    Multiple Failures (2 failures)
    org.junit.runners.model.TestTimedOutException: test timed out after 3 minutes
    com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=2228, name=cratedb[node_s1][force_merge][T#1], state=RUNNABLE, group=TGRP-OptimizeTableIntegrationTest]
    [...]
    Suppressed: com.carrotsearch.randomizedtesting.UncaughtExceptionError: Captured an uncaught exception in thread: Thread[id=2228, name=cratedb[node_s1][force_merge][T#1], state=RUNNABLE, group=TGRP-OptimizeTableIntegrationTest]
      Caused by: [vvsflujraykhqgprm.test/AJXhEptERj6dk7BNGYufpA][[vvsflujraykhqgprm.test/AJXhEptERj6dk7BNGYufpA][3]] org.elasticsearch.index.shard.ShardNotFoundException: no such shard
      at __randomizedtesting.SeedInfo.seed([FD210422454DDD47]:0)
      at org.elasticsearch.index.IndexService.getShard(IndexService.java:228)
      at org.elasticsearch.action.admin.indices.retention.TransportSyncRetentionLeasesAction.lambda$shardOperation$0(TransportSyncRetentionLeasesAction.java:96)
      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1095)
      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:619)
      at java.base/java.lang.Thread.run(Thread.java:1447)

(cherry picked from commit 7b8d2d04b9444dc1f62e7aa3d3b5ce8b80055c2d)