Allow ORDER BY on aggregations shadowed by alias
Fixes a regression in master.
Detected running the crate-python tests against the latest nightly. They
failed with:

    UnsupportedFeatureException: ORDER BY function 'count(id)' is not allowed. Only scalar functions can be used]
        [SQL: SELECT count(characters.id) AS count_1, characters.name AS characters_name
        FROM characters GROUP BY characters.name ORDER BY count(characters.id) DESC, characters.name