Fix flaky test_renamed_tables_can_be_queried_after_cluster_restart
Error: lock already held for [starting shard] with age [5007ms]

We need to wait until all shards are relocated and started after the restart
before querying tables

Follow up to https://github.com/crate/crate/commit/0b2b7f1da130bf2dad72beda8bde23f8a326c8b2

(cherry picked from commit fd98eb757408646d204ce5b3b53fe8f07f576e9c)