tests: Fix an issue causing ClassCastException when planning
Previously, a `ClassCastException` was thrown when attempting to plan
a join query with an uncorrelated subquery:

```
class io.crate.expression.symbol.Literal cannot be cast to class [Ljava.lang.Object; (io.crate.expression.symbol.Literal is in unnamed module of loader 'app'; [Ljava.lang.Object; is in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class io.crate.expression.symbol.Literal cannot be cast to class [Ljava.lang.Object; (io.crate.expression.symbol.Literal is in unnamed module of loader 'app'; [Ljava.lang.Object; is in module java.base of loader 'bootstrap')
	at __randomizedtesting.SeedInfo.seed([F78E2051B6B6F38A:A88EB4BCDEC1BB29]:0)
	at io.crate.types.ArrayType.convert(ArrayType.java:237)
	at io.crate.types.ArrayType.sanitizeValue(ArrayType.java:149)
	at io.crate.types.ArrayType.sanitizeValue(ArrayType.java:63)
	at io.crate.planner.operators.SubQueryAndParamBinder.visitSelectSymbol(SubQueryAndParamBinder.java:72)
	at io.crate.planner.operators.SubQueryAndParamBinder.visitSelectSymbol(SubQueryAndParamBinder.java:37)
	at io.crate.expression.symbol.SelectSymbol.accept(SelectSymbol.java:82)
	at io.crate.expression.symbol.FunctionCopyVisitor.twoArgs(FunctionCopyVisitor.java:97)
	at io.crate.expression.symbol.FunctionCopyVisitor.processAndMaybeCopy(FunctionCopyVisitor.java:57)
	at io.crate.expression.symbol.FunctionCopyVisitor.visitFunction(FunctionCopyVisitor.java:154)
	at io.crate.expression.symbol.FunctionCopyVisitor.visitFunction(FunctionCopyVisitor.java:40)
	at io.crate.expression.symbol.Function.accept(Function.java:185)
	at io.crate.planner.operators.SubQueryAndParamBinder.apply(SubQueryAndParamBinder.java:84)
	at io.crate.planner.operators.SubQueryAndParamBinder.apply(SubQueryAndParamBinder.java:37)
	at java.base/java.util.function.Function.lambda$andThen$1(Function.java:88)
	at io.crate.analyze.WhereClause.map(WhereClause.java:188)
	at io.crate.planner.operators.Collect.createPhase(Collect.java:266)
```

Follows: #13037
(cherry picked from commit 27ed554c23cb1d7e330800463f08bcb109a2fb6e)