Fix IndexName decode error on sys.allocation queries
`testNumberOfShardsOfAPartitionCanBeIncreased` was flaky and could fail with:

    io.crate.exceptions.SQLParseException: Invalid index name: .resized.m..partitioned.tbl.04132
    [...]
    at java.base/java.lang.Thread.run(Thread.java:1516)
    Caused by: java.lang.IllegalArgumentException: Invalid index name: .resized.m..partitioned.tbl.04132
      at io.crate.metadata.IndexName.decode(IndexName.java:123)
      at io.crate.expression.reference.sys.shard.SysAllocations.createSysAllocations(SysAllocations.java:101)
      at io.crate.expression.reference.sys.shard.SysAllocations.lambda$iterator$0(SysAllocations.java:83)

(cherry picked from commit 9fa5060f2836efa83c4c021b6f8773a188c72092)

# Conflicts:
#	docs/appendices/release-notes/6.3.2.rst