Try fix flaky test_types_with_storage_can_be_inserted_and_queried
Generates the second value based on the extended type. This matters for
object types to ensure the second value's inner type matches the first
values.

Should fix:

    io.crate.exceptions.SQLParseException: Cannot cast object element `x` with value `30257302154.0916198332508140` to type `numeric(22,16)`
      at __randomizedtesting.SeedInfo.seed([7AA865FBD8A7CAE9:5FB6988706FCB857]:0)
      at io.crate.exceptions.SQLExceptions.esToCrateException(SQLExceptions.java:195)
      at io.crate.exceptions.SQLExceptions.prepareForClientTransmission(SQLExceptions.java:184)
      at io.crate.testing.SQLTransportExecutor.lambda$execute$1(SQLTransportExecutor.java:295)
      at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:1011)
      at java.base/java.util.concurrent.CompletableFuture.uniExceptionallyStage(CompletableFuture.java:1029)
      at java.base/java.util.concurrent.CompletableFuture.exceptionally(CompletableFuture.java:2423)
      at io.crate.testing.SQLTransportExecutor.execute(SQLTransportExecutor.java:294)
      at io.crate.testing.SQLTransportExecutor.executeTransportOrJdbc(SQLTransportExecutor.java:227)
      at io.crate.testing.SQLTransportExecutor.exec(SQLTransportExecutor.java:130)
      at org.elasticsearch.test.IntegTestCase.execute(IntegTestCase.java:1547)
      at io.crate.integrationtests.TransportSQLActionTest.test_types_with_storage_can_be_inserted_and_queried(TransportSQLActionTest.java:1913)
      Caused by: io.crate.exceptions.ConversionException: Cannot cast object element `x` with value `30257302154.0916198332508140` to type `numeric(22,16)`

(Wasn't able to reproduce the issue, this fix is based on a best guess)