Avoid NPEs in PgClientTest
The mocked session caused errors in the log:

    [2025-04-07T16:14:17,907][WARN ][i.n.u.c.DefaultPromise   ] [[cratedb[netty-worker][T#6]]] An exception was thrown by io.crate.protocols.postgres.PostgresWireProtocol$$Lambda/0x00007f75834c0670.operationComplete()
    java.lang.NullPointerException: Cannot invoke "io.crate.metadata.settings.CoordinatorSessionSettings.dateStyle()" because "sessionSettings" is null
            at io.crate.protocols.postgres.PostgresWireProtocol.sendParams(PostgresWireProtocol.java:517) ~[classes/:?]
            at io.crate.protocols.postgres.PostgresWireProtocol.lambda$0(PostgresWireProtocol.java:462) ~[classes/:?]
            at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:603) [netty-common-4.2.0.Final.jar:4.2.0.Final]
            at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:570) [netty-common-4.2.0.Final.jar:4.2.0.Final]
            at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:505) [netty-common-4.2.0.Final.jar:4.2.0.Final]
            at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:198) [netty-common-4.2.0.Final.jar:4.2.0.Final]
            at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95) [netty-transport-4.2.0.Final.jar:4.2.0.Final]
            at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30) [netty-transport-4.2.0.Final.jar:4.2.0.Final]
            at io.crate.protocols.postgres.PostgresWireProtocol.finishAuthentication(PostgresWireProtocol.java:462) [classes/:?]
            at io.crate.protocols.postgres.PostgresWireProtocol.initAuthentication(PostgresWireProtocol.java:447) [classes/:?]