Extend gradle logging to include stacktraces
Before on an error only the exception message was printed without the
stacktrace:

    SQLActionException: INTERNAL_SERVER_ERROR 5000 VersionConflictEngineException: [default][1]: version conflict, current [2], provided [1]

Now the the stacktraces are printed as well. This should make it easier
to investigate failures happening on travis or jenkins:

    SQLActionException: INTERNAL_SERVER_ERROR 5000 VersionConflictEngineException: [default][1]: version conflict, current [2], provided [1]
	at __randomizedtesting.SeedInfo.seed([77EA16E28A5A1C17:90F9683BBC4E8210]:0)
	at org.elasticsearch.index.engine.InternalEngine.innerDelete(InternalEngine.java:598)
	at org.elasticsearch.index.engine.InternalEngine.delete(InternalEngine.java:558)
        [...]