Tests: Update hadoop version used in tests
Looking at http://www-eu.apache.org/dist/hadoop/common/ it appears that
`2.8.1` is no longer available.

This also improves the error reporting in such a case because before it
only printed a cryptic error:

    Test-module import failures:

    Module: tests

    urllib.error.HTTPError: HTTP Error 404: Not Found