Ignore setting change if engine is already closed
A AlreadyClosedException in the engine switch logic can happen if a
subscription is dropped and immediately after the table is deleted.
Parts of the subscription change are async and it can race with closing
of the table.

    [2022-04-27T06:05:20,424][WARN ][o.e.i.IndexService       ] [[cratedb[subscriber1][clusterApplierService#updateTask][T#1]]] [.partitioned.t1.04132] [2] failed to notify shard about setting change
    org.apache.lucene.store.AlreadyClosedException: engine is closed
    	at org.elasticsearch.index.shard.IndexShard.getEngine(IndexShard.java:2441) ~[crate-server.jar:?]
    	at org.elasticsearch.index.shard.IndexShard.sync(IndexShard.java:3011) ~[crate-server.jar:?]
    	at org.elasticsearch.index.shard.IndexShard.resetEngineToGlobalCheckpoint(IndexShard.java:3334) ~[crate-server.jar:?]
    	at org.elasticsearch.index.shard.IndexShardOperationPermits.blockOperations(IndexShardOperationPermits.java:110) ~[crate-server.jar:?]
    	at org.elasticsearch.index.shard.IndexShard.onSettingsChanged(IndexShard.java:1811) ~[crate-server.jar:?]
    	at org.elasticsearch.index.IndexService.updateMetadata(IndexService.java:571) [crate-server.jar:?]