Trim long durations for sys.job_metrics
We're only tracking durations up to 10 minutes, anything longer caused a
`ArrayIndexOutOfBoundsException`:

    ArrayIndexOutOfBoundsException: value outside of histogram covered
    range. Caused by: java.lang.IndexOutOfBoundsException: index 12669]
    occurred using: {"stmt": "COPY benchmarks.query_tests FROM
    's3://crate-stresstest-data/query-tests/*.json'"}

This changes the logic to normalize the durations to at most 10 minutes.