Make error more user friendly if a user attempts to decommission a node
Instead of:

    UnsupportedFeatureException: Can't handle "AnalyzedDecommissionNodeStatement{nodeIdOrName=Literal{Wilde Leck, type=string}}

The users will now get:

    User "<name>" is not authorized to execute statement