Fix serialization of DecomissionNodeRequest
`writeTo` of `TransportRequest` writes the parent taskId, the `reader`
for `DecomissionNodeRequest` used in the
`TransportDecomissionNodeAction` never read the taskId but returned a
singleton.

This led to a error:

    IllegalStateException: Message not fully read (request) for requestId [135130976], action [internal:crate:sql/decommission/node], available [0]; resetting

The blackbox tests never caught this issue because we always used the
client connected to the node we wanted to decommission, so the
serialization was never used.