Don't increment ref count in RefCountedItem on itemFactory errors
If `SharedShardContext.acquireSearcher` raises an error, consumers don't
receive the searcher instance and cannot close it.

That could lead to errors like:

    java.lang.IllegalStateException: Some shards are still open after the threadpool terminated. Something is leaking index readers or store references.
    	at __randomizedtesting.SeedInfo.seed([F2EBE6B07579FC27:E5694F811F06614B]:0)
    	at org.elasticsearch.node.Node.awaitClose(Node.java:1212)
    	at org.elasticsearch.test.TestCluster$NodeAndClient.close(TestCluster.java:1072)
    	at io.crate.common.io.IOUtils.close(IOUtils.java:98)
    	at io.crate.common.io.IOUtils.close(IOUtils.java:80)
    	at org.elasticsearch.test.TestCluster.close(TestCluster.java:922)
    	at io.crate.integrationtests.PgTunnelLogicalReplicationITest.stopCluster(PgTunnelLogicalReplicationITest.java:117)
    	at io.crate.integrationtests.PgTunnelLogicalReplicationITest.clearClusters(PgTunnelLogicalReplicationITest.java:131)

(cherry picked from commit 71fdfc34e7a4105ddf422409c1b2178810f8e104)