Fix NullPointerException of `crate-node` with missing config
Before:

    ↪  ./app/build/install/crate/bin/crate-node unsafe-bootstrap
    Exception in thread "main" java.lang.NullPointerException: supplier.get()
            at java.base/java.util.Objects.requireNonNull(Objects.java:246)
            at java.base/java.util.Objects.requireNonNullElseGet(Objects.java:321)
            at org.elasticsearch.cli.EnvironmentAwareCommand.createEnv(EnvironmentAwareCommand.java:89)
            at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:84)
            at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
            at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
            at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
            at org.elasticsearch.cli.Command.main(Command.java:90)
            at org.elasticsearch.cluster.coordination.NodeToolCli.main(NodeToolCli.java:45)

After:

    ↪  ./app/build/install/crate/bin/crate-node unsafe-bootstrap
    ERROR: the system property [es.path.conf] must be set. Specify with -Cpath.conf=<path>