ignore errors during listing of snapshots of a repository
``select * from sys.snapshots`` should never throw an error.

e.g.: if a repo was registered and the folder of the repo is
then deleted it would throw an RepositoryException

    RepositoryException: [repo1] failed to list snapshots
    in repository
    Caused by: java.io.FileNotFoundException: /tmp/index (No
    such file or directory)