Try fix flaky testPreferCopyCanPerformNoopRecovery
Failed with:

    java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because "io.crate.testing.SQLResponse.rows()[0][0]" is null
    	at __randomizedtesting.SeedInfo.seed([568A895E0BBDE298:C0CD333FC36536CD]:0)
    	at org.elasticsearch.gateway.ReplicaShardAllocatorIT.lambda$8(ReplicaShardAllocatorIT.java:397)
    	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:697)
    	at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:683)
    	at org.elasticsearch.gateway.ReplicaShardAllocatorIT.ensureActivePeerRecoveryRetentionLeasesAdvanced(ReplicaShardAllocatorIT.java:390)
    	at org.elasticsearch.gateway.ReplicaShardAllocatorIT.testPreferCopyCanPerformNoopRecovery(ReplicaShardAllocatorIT.java:100)

The query is in a `assertBusy` block but NPE's aren't retried.