Fix MemorySegmentIndexInputProvider lookup failures in jmh benchmarks
Running `java -jar benchmarks/target/benchmarks.jar` led to errors like:

    java.lang.LinkageError: MemorySegmentIndexInputProvider is missing in Lucene JAR file
            at org.apache.lucene.store.MMapDirectory.lookupProvider(MMapDirectory.java:446)
            at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
            at org.apache.lucene.store.MMapDirectory.doPrivileged(MMapDirectory.java:404)
            at org.apache.lucene.store.MMapDirectory.<clinit>(MMapDirectory.java:462)
            at org.apache.lucene.store.FSDirectory.open(FSDirectory.java:161)
            at org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:203)
            at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:259)
            at org.elasticsearch.node.Node.<init>(Node.java:319)
            at io.crate.analyze.PreExecutionBenchmark.setup(PreExecutionBenchmark.java:77)

Since we upgraded to Lucene 9.10, because Lucene makes use of
multi-releases JARs (https://openjdk.org/jeps/238)

The uberjar we generate for the benchmarks must be marked as
multi-release JAR as well, otherwise `MemorySegmentIndexInputProvider`
isn't available in the classpath.