Fix NPE in testDoesNotExceedLowWatermarkWhenRebalancing
SET GLOBAL needs to run before setting the disk usage function,
otherwise the event listener doesn't trigger and the
`masterAppliedClusterState` reference is null.

    java.lang.NullPointerException: Cannot invoke "org.elasticsearch.cluster.ClusterState.getRoutingNodes()" because the return value of "java.util.concurrent.atomic.AtomicReference.get()" is null
            at io.crate.integrationtests.DiskUsagesITest.lambda$14(DiskUsagesITest.java:238) ~[test-classes/:?]
            at org.elasticsearch.cluster.MockInternalClusterInfoService.lambda$2(MockInternalClusterInfoService.java:117) ~[test-classes/:?]

Looks like this didn't cause the test to fail, but the error is
confusing in the test output