Fix flaky testPreferCopyCanPerformNoopRecovery
    java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because "io.crate.testing.SQLResponse.rows()[0][0]" is null
      at __randomizedtesting.SeedInfo.seed([D7AD691DC26EFDE8:489240EBBEB7B005]:0)
      at org.elasticsearch.gateway.ReplicaShardAllocatorIT.lambda$ensureActivePeerRecoveryRetentionLeasesAdvanced$0(ReplicaShardAllocatorIT.java:384)
      at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:697)
      at org.elasticsearch.test.ESTestCase.assertBusy(ESTestCase.java:683)
      at org.elasticsearch.gateway.ReplicaShardAllocatorIT.ensureActivePeerRecoveryRetentionLeasesAdvanced(ReplicaShardAllocatorIT.java:377)
      at org.elasticsearch.gateway.ReplicaShardAllocatorIT.testPreferCopyCanPerformNoopRecovery(ReplicaShardAllocatorIT.java:93)