Fix github actions `vale` run
Currently it throws:
```
  /home/runner/vale --output=/home/runner/work/_actions/errata-ai/vale-action/v2.1.1/lib/rdjsonl.tmpl docs/
  E100 [lintRST] Runtime error

  rst2html not found

  Execution stopped with code 1.
Error: Vale and reviewdog exited with status code: 2
```

According to their docs:
``
If you're using a markup format other than Markdown, you may need to install an external parser before calling vale-action:

  # For AsciiDoc users:
  - name: Install Asciidoctor
    run: sudo apt-get install -y asciidoctor

  # For reStructuredText users:
  - name: Install docutils
    run: sudo apt-get install -y docutils
```

Follows: #18524