Improve error msg and docs for `date_bin`.
`date_bin` function doesn't allow intervals with months and/or year
units. Improve error message and docs. The behaviour is compatible with
PostgreSQL:

```
matriv=> SELECT date_bin('1 month 2 hours'::INTERVAL, ts, '2021-01-01T05:00:00Z'::TIMESTAMP)
FROM unnest(ARRAY['2021-01-01T08:30:10Z']::TIMESTAMP[]) as tbl(ts);
ERROR:  timestamps cannot be binned into intervals containing months or years
```

(cherry picked from commit 579b83afa5c1dbb070d1d0b7b14503417ae374b8)