Rename and reallocate index names again for table swap/rename
It was possible to end up with duplicate index names in the cluster if
creating a partition on a swapped table:

    create table tbl1 (x int, p int) partitioned by (p);
    create table tbl2 (x int, p int) partitioned by (p);
    insert into tbl1 (x, p) values (1, 1);
    alter cluster swap table tbl1 to tbl2;
    insert into tbl1 (x, p) values (1, 1);

This would then break the snapshot functionality, leading to errors
like:

    java.lang.IllegalStateException: Duplicate key foo..partitioned.tbl.ident (attempted merging values [foo..partitioned.tbl.ident/HPt5VVqgRqi31lldo6Kl-Q] and [foo..partitioned.tbl.ident/VQ3-qi4ESoqXnS_j9QrMNA])
    at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:135)
    at org.elasticsearch.snapshots.SnapshotShardsService.lambda$startNewShards$0(SnapshotShardsService.java:250)

To fix this properly we'll probably need to move away from deriving the
index name from the table (https://github.com/crate/crate/pull/19726)

But given the scope of that change, and given that there are/were a few
more index name decoding issues, this opts to rename the names again for
the hotfix