Apply writePendingMessage write in callback change to portalSuspended case
Follow up to https://github.com/crate/crate/pull/18417
Didn't verify yet if related, but this came to mind seeing node-postgres
failures:

    FAIL ./cratedb.test.js
      ✕ can use cursor to fetch subset of result with many reads (210 ms)
      ✕ can use cursor to fetch full result with many reads (2 ms)
      queries on table
        ✓ Can insert timestamp via parameter (679 ms)
        ✓ Can insert multiple values (456 ms)
        ✓ Can use update returning (325 ms)

      ● can use cursor to fetch subset of result with many reads
        expect(received).toHaveLength(expected)

        Expected length: 10
        Received length: 0
        Received array:  []
          39 |   expect(res1).toHaveLength(5);
          40 |   expect(res2).toHaveLength(10);
        > 41 |   expect(res3).toHaveLength(10);
             |                ^
          42 |
          43 |   await cursor.close();
          44 | });
          at Object.toHaveLength (cratedb.test.js:41:16)
      ● can use cursor to fetch full result with many reads
        error: Cannot find portal: C_1
          at Parser.parseErrorMessage (node_modules/pg-protocol/src/parser.ts:369:69)
          at Parser.handlePacket (node_modules/pg-protocol/src/parser.ts:188:21)
          at Parser.parse (node_modules/pg-protocol/src/parser.ts:103:30)
          at Socket.<anonymous> (node_modules/pg-protocol/src/index.ts:7:48)

(cherry picked from commit 75c665deeeb3fc1f41f9347b3cc90e0a263405c6)

# Conflicts:
#	server/src/main/java/io/crate/protocols/postgres/ResultSetReceiver.java