Fix flaky test_batch_inserts_with_mixed_threaded_execute
    java.lang.NullPointerException: Cannot invoke "io.netty.buffer.ByteBuf.release()" because "buf" is null
    	at __randomizedtesting.SeedInfo.seed([11647B3FEEDC5C1A:3402C04536B9E7E1]:0)
    	at io.crate.protocols.postgres.PostgresWireProtocolTest.readCommandComplete(PostgresWireProtocolTest.java:884)
    	at io.crate.protocols.postgres.PostgresWireProtocolTest.test_batch_inserts_with_mixed_threaded_execute(PostgresWireProtocolTest.java:865)