Replace sjk jmx client with java jmx queries via jnius
Download of the sjk client run into 403. Probably because of missing(?)
user-agent in the urlretrieve call:

    Traceback (most recent call last):
    File "/var/lib/jenkins/workspace/CrateDB/crate_on_pr/blackbox/test_jmx.py", line 193, in test_mbean_cluster_state_version
      jmx_client = JmxClient(JMX_PORT)
    File "/var/lib/jenkins/workspace/CrateDB/crate_on_pr/blackbox/test_jmx.py", line 68, in __init__
      self.jmx_path = self._get_jmx()
    File "/var/lib/jenkins/workspace/CrateDB/crate_on_pr/blackbox/test_jmx.py", line 76, in _get_jmx
      urlretrieve(JmxClient.SJK_JAR_URL, jar_path)
    File "/usr/lib/python3.10/urllib/request.py", line 241, in urlretrieve
      with contextlib.closing(urlopen(url, data)) as fp:
    File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
      return opener.open(url, data, timeout)
    File "/usr/lib/python3.10/urllib/request.py", line 525, in open
      response = meth(req, response)
    File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
      response = self.parent.error(
    File "/usr/lib/python3.10/urllib/request.py", line 563, in error
      return self._call_chain(*args)
    File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
      result = func(*args)
    File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
      raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 403: Forbidden

Used this as an opportunity to try out using the Java JMX classes to
query the beans via jnius to avoid the stdout parsing

(cherry picked from commit ecc4890426a5e3cf38ed6bd46d1d8e3d8030f1d2)