Fix flaky PrivilegesIntegrationTest
Became flaky with https://github.com/crate/crate/pull/18827 due to two
test methods creating the same function without drop function in the
teardown:

    org.postgresql.util.PSQLException:
    ERROR: User defined Function 'my_schema.foo(bigint)' already exists.
      Where: io.crate.expression.udf.UserDefinedFunctionService.putFunction(UserDefinedFunctionService.java:181)
    io.crate.expression.udf.UserDefinedFunctionService$1.execute(UserDefinedFunctionService.java:102)
    org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45)
    org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:664)
    org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:281)
    org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:176)
    org.elasticsearch.cluster.service.MasterService.lambda$doStart$0(MasterService.java:122)
    org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:170)
    org.elasticsearch.cluster.service.BatchedTask.run(BatchedTask.java:71)
    org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:208)
    org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:171)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
    java.lang.Thread.run(Thread.java:1474)
    	at __randomizedtesting.SeedInfo.seed([9A2F090BD8464E65:9F196E470CC6AA77]:0)