Move fix for corrupted metadata to a command
There has been a scenario discovered, with tables created in `4.3.3`
where the automatic fix of corrupted metadata due to a table swap
statements like:
```
ALTER CLUSTER SWAP TABLE "myschema"."mytable" TO "myschema.mytable"
```
led to a different issues, with node/cluster not starting up:
```
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: index and alias names need to be unique, but the following duplicates were found [doc.test (alias of [doc.test/30EcwHYoThW5UU0q4JFELA])]
	at org.elasticsearch.bootstrap.StartupExceptionProxy.<init>(StartupExceptionProxy.java:30) ~[main/:?]
	at io.crate.bootstrap.CrateDB.init(CrateDB.java:162) ~[main/:?]
	at io.crate.bootstrap.CrateDB.execute(CrateDB.java:138) ~[main/:?]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:81) ~[main/:?]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[main/:?]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[main/:?]
	at io.crate.bootstrap.CrateDB.main(CrateDB.java:91) ~[main/:?]
	at io.crate.bootstrap.CrateDB.main(CrateDB.java:84) ~[main/:?]
Caused by: java.lang.IllegalStateException: index and alias names need to be unique, but the following duplicates were found [doc.test (alias of [doc.test/30EcwHYoThW5UU0q4JFELA])]
	at org.elasticsearch.cluster.metadata.Metadata$Builder.build(Metadata.java:1072) ~[main/:?]
	at io.crate.metadata.bugfix.CorruptedMetadataFixer.fixCorruptionCausedBySwapTableBug(CorruptedMetadataFixer.java:127) ~[main/:?]
	at org.elasticsearch.gateway.GatewayMetaState.upgradeMetadataForNode(GatewayMetaState.java:201) ~[main/:?]
	at org.elasticsearch.gateway.GatewayMetaState.start(GatewayMetaState.java:135) ~[main/:?]
	at org.elasticsearch.node.Node.start(Node.java:943) ~[main/:?]
	at org.elasticsearch.bootstrap.BootstrapProxy.start(BootstrapProxy.java:204) ~[main/:?]
	at org.elasticsearch.bootstrap.BootstrapProxy.init(BootstrapProxy.java:268) ~[main/:?]
	at io.crate.bootstrap.CrateDB.init(CrateDB.java:158) ~[main/:?]
	... 6 more
```

Extract the fix into a command that can be run with `crate-node fix-corrupted-metadata`

Follows: #13404
Closes: #13617