Raise nicer error on string -> object casts
Instead of:

    java.lang.RuntimeException: com.fasterxml.jackson.core.JsonParseException: Unrecognized token

It now shows a regular cast error:

    Cannot cast value `foo` to type `object`