Fix flaky test_types_with_storage_can_be_inserted_and_queried
Follow up to https://github.com/crate/crate/pull/14437

Test failed if an object randomized to have a child float_vector due to
floating arithmetic:

    java.lang.AssertionError: [primary key lookup output must match regular select output for type object]
    Expecting Object[]:
      [{"x"=[0.21486431f]}, {"x"=[0.21486431f]}, "{"id":1,"x":{"x":[0.21486431]}}"]
    to contain:
      [{"x"=[0.21486431f]}, {"x"=[0.21486431f]}, "{"id":1,"x":{"x":[0.21486431]}}"]
    but could not find the following object(s):
      [{"x"=[0.21486431f]}, {"x"=[0.21486431f]}]

    at __randomizedtesting.SeedInfo.seed([EB5282A23639810D:CE4C7FDEE862F3B3]:0)
    at io.crate.integrationtests.TransportSQLActionTest.test_types_with_storage_can_be_inserted_and_queried(TransportSQLActionTest.java:1996)